### ISSUE TITLE
Issue building for My Mac (Mac Catalyst) 

### ISSUE THREAD

**Issue by simsaens** [steventroughtonsmith/CatalystEffectViewChrome#1]
After configuring code signing and attempting to build for _My Mac (Mac Catalyst)_  I get a sequence of `'swift_name' attribute argument must be a string literal specifying a Swift function name` errors in the UIKit header files

I poked around, tried removing and adding code, tried removing the AppKit integration framework, but nothing resolves this. Possibly a project setting I missed or an issue with the latest Xcode

The iOS destinations (_My Mac (Designed for iPad)_, and any _iOS Simulator_) work just fine, but obviously can't show the intended effect

<img width="1896" alt="image" src="https://user-images.githubusercontent.com/816857/156174913-a112f21e-849d-4c48-a6f4-a1ae1d687408.png">

**Comment by steventroughtonsmith** [comment]
What version of Xcode are you using? I've pulled from the repo again and it builds cleanly on Xcode 13.2.1 (13C100). I have not tried on the prerelease version of Xcode. It could be that the warnings-as-errors setting has included some new warnings in the SDK, and you might need to turn it off. Good to file a radar if SDK changes break the build — Apple's been getting bad at that, lately

**Comment by simsaens** [comment]
I am not on the latest Xcode, which I didn't realise! Mine is Version 13.2 (13C90). Will update and try again

Interestingly, I was able to use all the concepts from your code successfully in another project (the splash screen I was posting about), so it's likely an oddity on my end

**Comment by simsaens** [comment]
Hmm I get the same issue on the latest version 13.2.1 (13C100). I'll have to try restarting my Mac, clearing Xcode settings, and other things. Seems likely it's an issue with my setup

**Comment by saurabhsharan** [comment]
@TwoLivesLeft I am also getting the same build error (macOS 12.4, Xcode 13.4.1). Did you ever figure this out?

**Comment by steventroughtonsmith** [comment]
> @TwoLivesLeft I am also getting the same build error (macOS 12.4, Xcode 13.4.1). Did you ever figure this out?

For anybody coming to this at a later date — these errors present themselves when you use a Swift snapshot from swift.org instead of Xcode's default toolchain. Using the built-in toolchain compiles cleanly
